import { h } from "@aduh95/async-jsx";

import Body from "./views/Body.js";
import Header from "./views/Header.js";
import Footer from "./views/Footer.js";

import "./privacy.scss";

export default (
  <Body>
    <Header />
    <main id="main-content">
      <h2>Privacy policy</h2>
      <p>
        We (e-Comas - eCommerce Made Simple) collect data about you on our
        website, for our own use, for marketing purposes and so that we can
        contact you. <br />
        Our data collection is mainly through forms on the website. When you
        fill out one of these forms – for example, telling us your name, email
        address and business size – we can use this information to contact you
        in the most relevant, personal way, whether by getting the right member
        of our team to call you, or by sending you emails that are relevant to
        your business.
        <br />
        Our forms and database software are provided by Pardot by Salesforce.
        <br />
        Occasionally we also collect data through LinkedIn, Facebook, Instagram
        and Twitter. For example, when we receive messages enquiring about our
        services, we will save your name and contact information so we can help
        you.
        <br />
        From time to time we may send you emails and newsletters with useful
        information about eCommerce. You can opt out of these by clicking the
        “unsubscribe” button.
      </p>

      <h2>Cookie policy</h2>

      <h3>What are cookies and similar technologies?</h3>

      <p>
        A cookie is a small piece of information, consisting of alphanumeric
        text file, that is placed on an internet user's hard drive or device. It
        is generated by a web page server, basically the computer that operates
        a website.
      </p>

      <p>
        The information a cookie contains is generated by the server and can be
        used by that server whenever a user visits the site which hosts the
        online services.
        <br />
        There are two types of cookies:
      </p>
      <ul>
        <li>
          Session cookies, which allow websites to recognize and link the
          actions of a user during a browsing session (e.g: cookies used to
          remember what a user has put in their shopping basket as they browse a
          site),
        </li>
        <li>
          Persistent cookies, which allow websites to remember users'
          preferences and choices (e.g: cookies used to target advertising).
        </li>
      </ul>
      <p>
        Similar technologies are technics or tools, using certain
        characteristics to identify devices so that visits to a website can be
        analysed. It includes, for example, HTML5 local storage, local Shared
        objects, fingerprinting techniques, tracking pixels and plugins.
      </p>

      <p>
        For ease of reference, cookies and similar technologies are referred as
        “Cookies”.
      </p>

      <h3>What cookies does this website use?</h3>

      <p>
        By default, this website doesn't use any cookie. This website embeds
        some other websites (such as YouTube, Pardot, etc.) that might use
        cookies on their own. When you try to access those area and you haven't
        yet decided if you agree with the use of cookies, a popup will be
        displayed asking you to choose to accept cookies. See Google's{" "}
        <a href="https://policies.google.com/technologies/cookies">
          Cookie policy page
        </a>{" "}
        for more information on their use of cookies when using YouTube. See
        SalesForce's{" "}
        <a href="https://www.salesforce.com/uk/company/privacy/full_privacy/">
          Privacy Statement
        </a>{" "}
        for more information on their use of cookies when using Pardot forms.
      </p>

      <h3>How can you control cookies?</h3>

      <p>
        You can manage your cookies preferences using our cookie Privacy Panel.
      </p>

      <p>
        You can also manage cookies and delete cookies using your browser
        settings. Browsers such as Chrome, Edge, Firefox and Safari give you the
        ability to accept, reject or delete cookies. Visit the “help center” for
        your browser to learn more.
        <br />
        You can also take advantage of industry programs that allow you to
        control the way companies advertise to you.
      </p>

      <h2>Legal information</h2>

      <h3>Purpose of this website</h3>

      <p>
        This website, as well as the contents including all information, text,
        graphics, images, hyperlinks and other material are for general
        information purpose about e-Comas.
      </p>

      <h3>Links to other websites</h3>

      <p>
        This website may contain links to other websites, which are provided
        solely as convenience to you and not as an endorsement by e-Comas of the
        contents of such other websites. e-Comas is not responsible for the
        content of any other websites and does not make any representations or
        warranties regarding any other websites or the contents or materials of
        such websites.
      </p>

      <h3>LIMITATION OF LIABILITY</h3>

      <p>
        IN NO EVENT WILL e-COMAS BE LIABLE TO ANY PARTY FOR ANY DIRECT,
        INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY
        TYPE WHATSOEVER RELATED TO OR ARISING FROM THIS WEB SITE OR ANY USE OF
        THIS WEBSITE, OR OF ANY SITE OR RESOURCE LINKED TO, REFERENCED, OR
        ACCESSED THROUGH THIS WEBSITE, OR FOR THE USE OR DOWNLOADING OF, OR
        ACCESS TO, ANY MATERIALS, INFORMATION, PRODUCTS, OR SERVICES, INCLUDING,
        WITHOUT LIMITATION, ANY LOST PROFITS, BUSINESS INTERRUPTION, LOST
        SAVINGS OR LOSS OF PROGRAMS OR OTHER DATA, EVEN IF e-COMAS IS EXPRESSLY
        ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS EXCLUSION AND WAIVER OF
        LIABILITY APPLIES TO ALL CAUSES OF ACTION, WHETHER BASED ON CONTRACT,
        WARRANTY, TORT, OR ANY OTHER LEGAL THEORIES.
      </p>

      <p>
        For more information, contact the webmaster at{" "}
        <a href="mailto:it@e-comas.com">it@e-comas.com</a>.
      </p>
    </main>
    <Footer />
  </Body>
).then((elem) => document.body.append(elem));
